### PR TITLE
Multiplayer support with MPAPI

### PR DESCRIPTION
**Pull request by notfood**
- Implements Multiplayer support natively.
- Very self contained and easy to maintain.
- All Hospitality features are working.
- It'll need a recompile, I'm not including the dll.

### CODE REVIEW

**Comment by OrionFive** [comment]
I didn't get around to updating with this yet. But many thanks!

**Comment by OrionFive** [comment]
I didn't test it myself, but someone with multiplayer enabled immediately got exceptions:

https://gist.github.com/HugsLibRecordKeeper/c312d555ec35640f8f7f2491d9d30ded

Can you help me with this, @notfood?

**Comment by OrionFive** [comment]
And another one, when using the guest menu: https://steamcommunity.com/workshop/filedetails/discussion/753498552/5188663423647224773/

**Comment by OrionFive** [comment]
I've rolled back the Steam version, since it seems to break almost everyone's game.

**Comment by OrionFive** [comment]
Hm, the guest menu problem I can actually reproduce (should have tested better). People losing all their pawns and beds (first issue) I can't reproduce.
EDIT: Uhm.... What happens when people run Multiplayer.API.Dummy.WatchBegin () but don't have the Multiplayer mod?

**Comment by OrionFive** [comment]
So I think issue 1 happens if you do have the multiplayer mod installed and active, and issue 2 happens when you don't have the mod.

**Comment by notfood** [comment]
You know... you need to include 0MultiplayerApi.dll, without it, it'll fail as described.

**Pull request merged**
