### PR TITLE
Blu3wolf licensing

### LINKED ISSUE #1: CC0 license in README
So, the CC0 license is an all or nothing thing. It by definition applies to you, not some third party - and it makes the statement that you are waiving all rights to your work. 

Creative Commons recommend that their licenses not be used for software, and for their own software, they use free and open source licenses, such as the Free Software Foundation's GNU General Public License. 

Its worth noting that as the sole creator of a work, nothing prevents you from releasing your work under multiple licenses. You are capable of releasing your work under a FOS license, while also granting a non exclusive license to Ludeon Studios to use your work in a commercial offering, separately from the FOS license. 

I would recommend licensing any art assets that are in the mod, under the CC license of your choice, and licensing the code assets separately, ideally under a FOSS license, such as the LGPL.

In short though, you can't really license your work as CC0 for one party,  CC-BY-SA 4.0I for everyone else. 

The only other quirky part is when you are not the sole author. For FOSS licensing, this is not really considered an issue, but if you want to retain sole rights to your work, I would recommend checking our a Contributor Licensing Agreement, that essentially requires any contributions to your mod (should you accept them) be offered under whichever license you are planning on using.

### PR DESCRIPTION
**Pull request by Blu3wolf**
Ive updated the license included in the readme, as well as added the full text of the GPL in another file LICENSE. This would change the license of the code itself to be under the GPL, which is similar in purpose (but not the same) to the CC-BY-SA 4.0 it is currently available under (your existing license). The artwork remains under the CC license however. 

Closes #1

### CODE REVIEW

**Comment by Blu3wolf** [comment]
This does not add a Contributor License Agreement, which would indicate to any contributors making PRs whatever terms you felt appropriate. An obvious one would be that any submissions made would either be public domain, CC0, or made under an irrevocable license giving you full rights to those submissions. This would allow you to publish those submissions without concern of a contributor later complaining that they want their contribution removed. 

Yes, that is a headache. Yes, that is one of the things to consider when including other peoples work in your project.

**Comment by Blu3wolf** [comment]
Finally, I would recommend reading through the GPL before merging, just to confirm you are okay with the changes it makes. The Preamble section at the start of it largely explains the intent of the license. Be aware that as the licensor, you are not bound by the terms of the license. Publishing your mod today under the GPL, for example, does not prevent you from later publishing it as a commercial, closed source product. It does however prevent anyone else from doing so (except in this case ludeon, as you are offering them a separate license with full rights).

**Comment by OrionFive** [comment]
Looks good to me. Thanks!
A contributor license agreement does sound like a good addition, though. Is there an obvious choice which one to use?

**Comment by Blu3wolf** [comment]
well, not really. The simplest way is to ask that anyone submitting code releases it to the public domain, or under a CC0 license (essentially the same thing). Anyone can then use the code they submit to you, then. This includes you, and it means you can in turn re-release a future version of the mod under a different license, if you choose. It also means any future version of your mod (including contributed code) could still be used by Ludeon, should they choose to. This is a salient point, because if contributors only licensed their code to you under say the GPL, then that would prevent you from subsequently licensing that code to Ludeon separately. 

An alternative if you wanted contributors to retain copyright over their contributions, is to specify an irrevocable, royalty free license for contributions, so that you can use contributors code in the future, even following a change of heart. Should they decide to pull out, and request their contributions be removed, if they retain copyright and you do not have an irrevocable license to use their code, they can revoke their permission for you to use their contributions.

**Comment by Blu3wolf** [comment]
Im personally a fan of free open source software, and keeping that in mind, Id suggest just asking folks, before merging their work (and you can make this automatic with GitHub), if they would note that their contributions to your project are under a CC0 license. 

If you preferred to go the irrevocable license route, allowing contributors to retain copyright, you can get a premade license from Project Harmony (http://www.harmonyagreements.org/review.html)

**Comment by Blu3wolf** [comment]
submitted PR #3 to add a contributors guidelines file

**Pull request merged**
