### PR TITLE
Allow guests to sleep in beds with multiple spots

### PR DESCRIPTION
**Pull request by Taranchuk**
This PR will allow married guests to sleep together. Also needed for an upcoming mod adding bunk beds to allow guests to sleep in bunk beds.

### CODE REVIEW

**Comment by OrionFive** [comment]
This PR broke guest behavior. Multiple guests now claim the same bed but then both not sleep in it.

I'm gonna roll it back tomorrow, unless you want to fix it.

**Comment by Taranchuk** [comment]
Does it break with single or double beds?

**Comment by Taranchuk** [comment]
I think I'm seeing what's the issue. Pawns are claiming beds after approaching them but not when finding jobs. This makes it so multiple pawns can get multiple jobs with the same bed. I'm looking if there is a way to let pawns know that the bed is being claimed by other pawn.

**Comment by Taranchuk** [comment]
Okay so in vanilla pawns are claiming beds before going to beds. In the mod pawns are claiming beds after going to them. So we just need to change the order.

**Comment by Taranchuk** [comment]
https://github.com/OrionFive/Hospitality/pull/744
This PR should solve the issue.

**Pull request merged**
